"use client";

import React, { useState, useRef, useEffect } from "react";
import MemoryGame from "./MemoryGame";
import FocusGame from "./FocusGame";
import MindfulnessGame from "./MindfulnessGame";
import CreativeGame from "./CreativeGame";
import jsPDF from "jspdf";

/* ================= TYPES ================= */

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface Metrics {
  anxietyLevel: number;
  moodScore: number;
  stressLevel: number;
  sleepQuality: string;
  motivationLevel: number;
  socialEngagement: number;
}

/* ================= COMPONENT ================= */

export default function VentOut() {
  /* ---------------- State ---------------- */

  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      content:
        "Hello! I'm here to listen and support you. How are you feeling today?",
    },
  ]);

  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);

  const [metrics, setMetrics] = useState<Metrics>({
    anxietyLevel: 30,
    moodScore: 7,
    stressLevel: 40,
    sleepQuality: "good",
    motivationLevel: 75,
    socialEngagement: 60,
  });

  const [crisisAlert, setCrisisAlert] = useState<string | null>(null);

  const [activeGame, setActiveGame] = useState<string | null>(null);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  /* ================= AUTO SCROLL ================= */

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  /* ================= CHAT LOGIC ================= */

  const handleSendMessage = () => {
    if (!input.trim() || loading) return;

    const userText = input.toLowerCase();

    setMessages((prev) => [...prev, { role: "user", content: input }]);
    setInput("");
    setLoading(true);

    let reply = "I'm here for you. Tell me more 💛";
    let updated = { ...metrics };

    /* Positive */

    if (
      userText.includes("happy") ||
      userText.includes("good") ||
      userText.includes("great") ||
      userText.includes("fine") ||
      userText.includes("better")
    ) {
      reply = "That’s wonderful to hear! Keep going 🌟";

      updated.moodScore = Math.min(updated.moodScore + 1, 10);
      updated.stressLevel = Math.max(updated.stressLevel - 5, 0);
      updated.anxietyLevel = Math.max(updated.anxietyLevel - 3, 0);
    }

    /* Negative */

    else if (
      userText.includes("sad") ||
      userText.includes("tired") ||
      userText.includes("stress") ||
      userText.includes("depressed") ||
      userText.includes("pressure")
    ) {
      reply =
        "I'm really sorry you're feeling this way. You're not alone 💛 Want to talk about it?";

      updated.moodScore = Math.max(updated.moodScore - 1, 1);
      updated.stressLevel = Math.min(updated.stressLevel + 6, 100);
      updated.anxietyLevel = Math.min(updated.anxietyLevel + 5, 100);
    }

    /* Crisis */

    if (userText.includes("suicide") || userText.includes("dying")) {
      setCrisisAlert(
        "⚠️ You matter. Please reach out to a trusted person or mental health professional immediately."
      );
    } else {
      setCrisisAlert(null);
    }

    /* Response */

    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: reply },
      ]);

      setMetrics(updated);
      setLoading(false);
    }, 600);
  };

  /* ================= PDF ================= */

  const downloadReport = () => {
    const doc = new jsPDF();

    doc.setFont("helvetica");

    doc.setFontSize(20);
    doc.text("Monthly Wellness Report", 20, 20);

    doc.setFontSize(12);
    doc.text(`Mood Score: ${metrics.moodScore}/10`, 20, 40);
    doc.text(`Stress Level: ${metrics.stressLevel}%`, 20, 50);
    doc.text(`Anxiety Level: ${metrics.anxietyLevel}%`, 20, 60);
    doc.text(`Sleep Quality: ${metrics.sleepQuality}`, 20, 70);

    doc.line(20, 80, 190, 80);

    doc.setFontSize(11);
    doc.text("Generated by Bodha Setu Wellness System", 20, 95);

    doc.save("Wellness_Report.pdf");
  };

  /* ================= UI ================= */

  return (
    <div className="min-h-screen w-full bg-gray-50">
      <main className="w-full max-w-7xl mx-auto py-10 px-4 space-y-10">

        {/* Header */}

        <div>
          <h1 className="text-4xl font-bold text-gray-900">
            🌿 Wellness Corner
          </h1>
          <p className="mt-2 text-gray-600">
            Your personal mental wellness space
          </p>
        </div>

        {/* Dashboard */}

        <div className="bg-linear-to-br from-emerald-600 to-teal-600 rounded-xl shadow-lg p-8 text-white">

          <h2 className="text-3xl font-bold mb-6">
            🌱 Your Wellness Dashboard
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">

            <Stat title="Mood Score" value={`${metrics.moodScore}/10`} />

            <Stat title="Stress Level" value={`${metrics.stressLevel}%`} />

            <Stat title="Sleep Quality" value={metrics.sleepQuality} />

          </div>
        </div>

        {/* Main Section */}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">

          {/* Chat */}

          <div className="bg-white rounded-xl shadow-md p-6">

            <h2 className="text-2xl font-bold mb-4">
              💬 Wellness Chatbot
            </h2>

            {crisisAlert && (
              <div className="mb-4 p-4 bg-red-50 border-2 border-red-400 rounded-lg">
                <p className="text-red-800 font-semibold">
                  {crisisAlert}
                </p>
              </div>
            )}

            <div className="border rounded-lg p-4 h-80 overflow-y-auto bg-gray-50 mb-4">

              {messages.map((msg, i) => (
                <div
                  key={i}
                  className={`mb-3 flex ${
                    msg.role === "user"
                      ? "justify-end"
                      : "justify-start"
                  }`}
                >
                  <div
                    className={`px-4 py-2 rounded-lg max-w-xs text-sm ${
                      msg.role === "user"
                        ? "bg-emerald-600 text-white"
                        : "bg-gray-200"
                    }`}
                  >
                    {msg.content}
                  </div>
                </div>
              ))}

              {loading && (
                <p className="text-sm text-gray-400">Typing...</p>
              )}

              <div ref={messagesEndRef} />
            </div>

            <div className="flex gap-2">

              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) =>
                  e.key === "Enter" && handleSendMessage()
                }
                placeholder="Share your thoughts..."
                className="flex-1 px-4 py-2 border rounded-lg"
              />

              <button
                onClick={handleSendMessage}
                className="px-5 py-2 bg-emerald-600 text-white rounded-lg"
              >
                Send
              </button>

            </div>

          </div>

          {/* Analysis */}

          <div className="bg-white rounded-xl shadow-md p-6">

            <h2 className="text-2xl font-bold mb-4">
              📊 Behavioral Analysis
            </h2>

            <Progress
              label="Anxiety"
              value={metrics.anxietyLevel}
              color="bg-green-500"
            />

            <Progress
              label="Motivation"
              value={metrics.motivationLevel}
              color="bg-blue-500"
            />

            <Progress
              label="Social Engagement"
              value={metrics.socialEngagement}
              color="bg-yellow-500"
            />

            <Progress
              label="Sleep"
              value={65}
              color="bg-purple-500"
            />

            <button
              onClick={downloadReport}
              className="mt-6 w-full py-3 bg-blue-600 text-white rounded-xl"
            >
              📥 Download Report
            </button>

          </div>

        </div>

        {/* Games */}

        {activeGame && (
          <div className="fixed inset-0 bg-black/50 flex justify-center items-center z-50">

            <div className="bg-white max-w-2xl w-full p-6 rounded-xl relative">

              <button
                onClick={() => setActiveGame(null)}
                className="absolute top-3 right-3 text-xl"
              >
                ✖
              </button>

              {activeGame === "memory" && <MemoryGame />}
              {activeGame === "focus" && <FocusGame />}
              {activeGame === "mindfulness" && <MindfulnessGame />}
              {activeGame === "creative" && <CreativeGame />}

            </div>

          </div>
        )}

        {/* Games Grid */}

        <div className="bg-white p-6 rounded-xl shadow-md">

          <h2 className="text-2xl font-bold mb-6">
            🎮 Brain Games
          </h2>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-5">

            <Game
              icon="🧩"
              title="Memory"
              onClick={() => setActiveGame("memory")}
            />

            <Game
              icon="🎯"
              title="Focus"
              onClick={() => setActiveGame("focus")}
            />

            <Game
              icon="🧘"
              title="Mindfulness"
              onClick={() => setActiveGame("mindfulness")}
            />

            <Game
              icon="🎨"
              title="Creative"
              onClick={() => setActiveGame("creative")}
            />

          </div>

        </div>

      </main>
    </div>
  );
}

/* ================= UI ================= */

function Stat({ title, value }: any) {
  return (
    <div className="bg-white/10 p-5 rounded-lg">
      <p className="text-sm opacity-90">{title}</p>
      <p className="text-4xl font-bold mt-1">{value}</p>
    </div>
  );
}

function Progress({ label, value, color }: any) {
  return (
    <div className="mb-4">

      <div className="flex justify-between mb-1 text-sm font-medium">
        <span>{label}</span>
        <span>{value}%</span>
      </div>

      <div className="w-full bg-gray-200 h-3 rounded-full">

        <div
          className={`${color} h-3 rounded-full`}
          style={{ width: `${value}%` }}
        ></div>

      </div>

    </div>
  );
}

function Game({ icon, title, onClick }: any) {
  return (
    <div
      onClick={onClick}
      className="border rounded-xl p-5 text-center hover:shadow-lg cursor-pointer"
    >
      <div className="text-4xl mb-2">{icon}</div>
      <h3 className="font-semibold">{title}</h3>
    </div>
  );
}
